version: '3.8'
services:
  db:
      container_name: flask_app_pg
      image: postgres:13.2
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: flask_app_db
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 20s
        timeout: 10s
        retries: 10
      volumes:
        - ./.cache/infile:/infile
        - pg_data:/var/lib/postgresql/data/
  server:
      container_name: flask_app_server
      build: ./
      ports:
        - "5005:5005"
      links:
        - db:db
      depends_on:
        db:
          condition: service_healthy
volumes:
  pg_data: {}
