#!/bin/sh
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME to $APP_DB_USER;
  CREATE USER $TEST_DB_USER WITH PASSWORD '$TEST_DB_PASSWORD';
  CREATE DATABASE $TEST_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $TEST_DB_NAME to $TEST_DB_USER;
EOSQL
